[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_SITE_URL = "https://editors-hub.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
