[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  DISABLE_TYPE_CHECK = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs" 